module.exports = {
    SMILE: '🙂',
    SMILE_MEDIUM: '😃',
    SMILE_HARD: '😂',
    SAD: '😞',
    CRY_MEDIUM: '😢',
    CRY_HARD: '😭',
    ANGRY: '😑',
    ANGRY_RED: '😡',
    NO_COMMENT: '😶',
    SERIOUS: '😐',
    WOW: '😮',
    HOME: '🏠',
    SCHOOL: '🏢',
    LOVE:'❤️',
    LIKE:'👍',
}